# Generated by Django 2.2 on 2019-09-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0009_auto_20190911_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=123, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
