# Generated by Django 2.2.5 on 2019-09-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0014_auto_20190912_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
